
INSERT INTO contacts (id, name) VALUES ('1', 'Syer'),
('2', 'Ash'),
('3', 'Matteo'),
('4', 'Georgia'),
('5', 'Nico'),
('6', 'Lola'),
('7', 'Violet'),
('8', 'Zane'),
('9', 'Finn'),
('10', 'Paloma'),
('11', 'Alexis'),
('12', 'Maisie'),
('13', 'Whitney'),
('14', 'Donovan'),
('15', 'Ronnie'),
('16', 'Trinity'),
('17', 'Delilah'),
('18', 'Robbin'),
('19', 'Michele'),
('20', 'Cameron'),
('21', 'Willa'),
('22', 'Elvis'),
('23', 'Lesley'),
('24', 'Shannon'),
('25', 'Cortney'),
('26', 'Gail'),
('27', 'Allison'),
('28', 'Beckett')
;
